"""Build the curated RAGTruth QA demo-case asset from the on-disk test split.

Cases are copied verbatim from the RAGTruth QA test split with their real
word-level hallucination annotations; every message/answer hash is computed
from the actual content. The chips fill the editor for live faithfulness runs
(like the PsiloQA gallery) and carry NO scores.

The dataset was saved with a newer ``datasets`` feature schema than the pinned
env can parse, so this reads the Arrow file directly with pyarrow (a datasets
dependency, always present) instead of ``load_from_disk``.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import pyarrow as pa

REPO_ROOT = Path(__file__).resolve().parents[1]
DATASET_ROOT = Path(
    '/home/jovyan/ybelikova/sirin-final/data/datasets/ragtruth_qa'
)
TEST_ARROW = DATASET_ROOT / 'test' / 'data-00000-of-00001.arrow'
ASSET_PATH = REPO_ROOT / 'sirin/ui/assets/ragtruth_demo_cases.json'

Q_PREFIX = 'Briefly answer the following question:\n'
BEAR = (
    '\nBear in mind that your response should be strictly based on the '
    'following '
)
PASSAGES_MARK = ' passages:\n'
TAIL = (
    '\n\nIn case the passages do not contain the necessary information to '
    'answer the question'
)

# (dataset_index, short label, why_notable) — curated from the RAGTruth QA test
# split for model + hallucination-type diversity and short, readable contexts.
SELECTED_CASES = (
    (
        0,
        'Bowel movement & weight',
        'Faithful gpt-4 answer with zero hallucination spans — the supported '
        'baseline that stays grounded in the passages.',
    ),
    (
        4,
        'Carbon footprint',
        'One localized fabrication (Subtle Baseless): the closing list of '
        'reduction tactics is invented, not supported by any passage.',
    ),
    (
        138,
        'FEHA vs ADA',
        'Two conflicting spans (Evident Conflict): the employee-count '
        'thresholds for FEHA and the ADA are swapped/misstated versus the '
        'passages.',
    ),
    (
        721,
        'Patterned paint rollers',
        'One conflicting span (Evident Conflict): claims patterned rollers '
        '"stimulate the skin and provide a healthy glow", which no passage '
        'about paint rollers supports.',
    ),
)

DISCLOSURES = {
    'selection_disclosure': (
        'Curated from the held-out RAGTruth QA test split for demo clarity; '
        'chosen for short readable RAG contexts and a mix of supported and '
        'hallucinated answers.'
    ),
    'annotation_disclosure': (
        'Gold spans are RAGTruth human hallucination annotations over the '
        'answer text, hidden by default in the demo.'
    ),
    'source_disclosure': (
        'The answer was generated by the named model over the retrieved '
        'passages; SIRIN did not generate or score it — the chip fills the '
        'editor for a live run.'
    ),
    'license': 'see RAGTruth dataset license',
}


def read_test_rows() -> list[dict[str, Any]]:
    with pa.memory_map(str(TEST_ARROW), 'r') as source:
        try:
            table = pa.ipc.open_stream(source).read_all()
        except pa.lib.ArrowInvalid:
            source.seek(0)
            table = pa.ipc.open_file(source).read_all()
    return table.to_pylist()


def split_prompt(prompt: str) -> tuple[str, str]:
    """Return (question, passages) extracted from the RAG prompt template."""
    if not prompt.startswith(Q_PREFIX):
        raise ValueError('prompt does not follow the RAGTruth QA template')
    rest = prompt[len(Q_PREFIX):]
    bear_at = rest.find(BEAR)
    if bear_at < 0:
        raise ValueError('prompt is missing the passages preamble')
    question = rest[:bear_at]
    after = rest[bear_at + len(BEAR):]
    mark_at = after.find(PASSAGES_MARK)
    if mark_at < 0:
        raise ValueError('prompt is missing the passages marker')
    passages_and_tail = after[mark_at + len(PASSAGES_MARK):]
    tail_at = passages_and_tail.find(TAIL)
    if tail_at < 0:
        raise ValueError('prompt is missing the closing instruction')
    passages = passages_and_tail[:tail_at]
    if question not in prompt or passages not in prompt:
        raise ValueError('extracted question/passages are not verbatim')
    return question, passages


def canonical_messages_sha256(messages: list[dict[str, str]]) -> str:
    encoded = json.dumps(
        messages, ensure_ascii=False, separators=(',', ':')
    ).encode()
    return hashlib.sha256(encoded).hexdigest()


def build_case(
    row: dict[str, Any], index: int, label: str, why_notable: str
) -> dict[str, Any]:
    messages = [
        {'role': message['role'], 'content': message['content']}
        for message in row['input']
    ]
    if [message['role'] for message in messages] != ['user', 'assistant']:
        raise ValueError(f'Row {index} input must be a user/assistant pair')
    if row['prompt'] != messages[0]['content']:
        raise ValueError(f'Row {index} prompt must match the user message')
    if row['response'] != messages[1]['content']:
        raise ValueError(f'Row {index} response must match the assistant message')

    answer = row['response']
    question, context = split_prompt(row['prompt'])

    gold_spans = [[label_['start'], label_['end']] for label_ in row['labels']]
    for (start, end), annotation in zip(gold_spans, row['labels']):
        if not 0 <= start < end <= len(answer):
            raise ValueError(f'Row {index} gold span {[start, end]} is out of range')
        if answer[start:end] != annotation['text']:
            raise ValueError(f'Row {index} gold span text does not align to the answer')

    return {
        'case_id': f'ragtruth_qa_{row["model"]}_{index}',
        'label': f'RAGTruth: {label}',
        'why_notable': why_notable,
        'dataset': 'ragtruth_qa',
        'split': 'test',
        'dataset_index': index,
        'source_id': row['source_id'],
        'task_type': row['task_type'],
        'context': context,
        'question': question,
        'answer': answer,
        'messages': messages,
        'content_sha256': {
            'user': hashlib.sha256(messages[0]['content'].encode()).hexdigest(),
            'assistant': hashlib.sha256(
                messages[1]['content'].encode()
            ).hexdigest(),
        },
        'messages_sha256': canonical_messages_sha256(messages),
        'gold_spans': gold_spans,
        'gold_visibility': 'hidden',
        'source_answer_model': row['model'],
        **DISCLOSURES,
    }


def main() -> None:
    rows = read_test_rows()
    cases = [
        build_case(rows[index], index, label, why_notable)
        for index, label, why_notable in SELECTED_CASES
    ]
    payload = {
        'schema_version': 1,
        'source': str(DATASET_ROOT),
        'split': 'test',
        'cases': cases,
    }
    ASSET_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + '\n',
        encoding='utf-8',
    )
    print(f'Wrote {len(cases)} cases to {ASSET_PATH.relative_to(REPO_ROOT)}')


if __name__ == '__main__':
    main()
